---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about-us.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp lab.html $DEPLOYPATH
    - /bin/cp prof-harrington.html $DEPLOYPATH
    - /bin/cp publications.html $DEPLOYPATH
    - /bin/cp research.html $DEPLOYPATH
    - /bin/cp tingle.min.css $DEPLOYPATH
    - /bin/cp tingle.min.js $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH